spring.application.name=ArquiteturaHexagonal

#postgress docker
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres-hexagonal
spring.datasource.username=postgress
spring.datasource.password=postgress
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=auto
